appName: checkoutservice
containerPort: 5050
imageName: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice
imageVersion: sample-public-image-v0.10.2
containerEnv:
  - name: PORT
    value: "5050"
  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice:3550"
  - name: SHIPPING_SERVICE_ADDR
    value: "shippingservice:50051"
  - name: EMAIL_SERVICE_ADDR
    value: "emailservice:50051"
  - name: PAYMENT_SERVICE_ADDR
    value: "paymentservice:50052"
  - name: CURRENCY_SERVICE_ADDR
    value: "currencyservice:7000"
  - name: CART_SERVICE_ADDR
    value: "cartservice:7070"

servicePort: 5050