appName: checkoutservice
containerPort: 5050
imageName: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice
imageVersion: sample-public-image-v0.10.2
containerEnv:
  - envName: PORT
    envvalue: "5050"
    
  - envName: PRODUCT_CATALOG_SERVICE_ADDR
    envvalue: "productcatalogservice:3550"

  - envName: SHIPPING_SERVICE_ADDR
    envvalue: "shippingservice:50052"

  - envName: EMAIL_SERVICE_ADDR
    envvalue: "emailservice:5000"

  - envName: PAYMENT_SERVICE_ADDR
    envvalue: "paymentservice:50051"

  - envName: CURRENCY_SERVICE_ADDR
    envvalue: "currencyservice:7000"

  - envName: CART_SERVICE_ADDR
    envvalue: "cartservice:7070"

servicePort: 5050