appName: productcatalogservice
containerPort: 3550
imageName: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice
imageVersion: v0.10.1
containerEnv:
  - envName: PORT
    envvalue: "3550"
  - envName: DISABLE_PROFILER
    envvalue: "1"


servicePort: 3550