- name: Update packages
  ansible.builtin.apt:
    update_cache: yes
    
- name: Install requirment packages
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificates 

- name: Make dir gpg
  ansible.builtin.file:
    name: /etc/apt/keyrings
    state: directory

- name: Add Docker GPG apt Key  
  ansible.builtin.apt_key:
    url:  https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add source repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install docker
  ansible.builtin.apt:
    name:
      - docker-ce 
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Update packages
  ansible.builtin.apt:
    update_cache: yes
    force: yes
